fixtures:
  # use the forge modules so we can easily pin to a specific version
  forge_modules:
    stdlib: "puppetlabs/stdlib"
    python: "stankevich/python"
    vcsrepo: "puppetlabs/vcsrepo"
    epel: 'stahnma/epel'
    ini_config: 'tykeal/ini_config'
  symlinks:
    jjb: "#{source_dir}"
